### ISSUE TITLE
DB Browser SQL Lite 3.9.1 64 bit is not working??? NEED HELP ASAP

### ISSUE THREAD

**Issue by altair2258** [sqlitebrowser/dbhub-application#2]
![error db browser1](https://cloud.githubusercontent.com/assets/20593379/21346944/8f23de7a-c6cc-11e6-9e85-3894233229c9.png)
My software DB Browser SQL Lite 3.9.1 after installing isn't Working! The moment i try to run it it didn't.
 I have provided a screenshot of what error message is prompted. Plz help me out!!!
![error db browser](https://cloud.githubusercontent.com/assets/20593379/21346096/c4a102e8-c6c8-11e6-8d79-fcd19d22309b.png)

**Comment by justinclift** [comment]
Sorry for the delay @altair2258, I didn't realise anyone would be filing issues here for DB4S related things.

Did you manage to figure this out yet?

**Comment by altair2258** [comment]
Well even though i have 64bit windows but the 64bit setup caused hindrance while execution as u can see in my previous query!!! i am using the 32bit setup and its working PERFECTLY FINE!!!

**Comment by justinclift** [comment]
Ahhh cool.  Are you ok with keeping using the 32-bit version then? :smile:

As a thought, we do have some steps to follow for investigating this kind of problem more:

* https://github.com/sqlitebrowser/sqlitebrowser/issues/847#issuecomment-256713334
* https://github.com/sqlitebrowser/sqlitebrowser/issues/847#issuecomment-256763348

They're not for the faint of heart though. :wink:

Personally speaking, if the 32-bit version is working fine I'd recommend just sticking with that for now. 😀

**Comment by altair2258** [comment]
True will stick to 32-bit! but still i would like to know about the problem in 64-bit .exe file launch just for knowledge if you think that's ok! thanks Justin for suggestions! and help!

**Comment by justinclift** [comment]
Sure, that's no problem at all.  You'll need to download and investigate with the utilities mentioned in the links above.  It will take time and effort, but you'll probably learn heaps (and hopefully figure out the solution too). 😀

**Comment by justinclift** [comment]
Just noticed you've forked this repository too.  This one is for our (in development) website application.

If you're wanting the DB Browser for SQLite one instead, it's here::

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser

Just mentioning it in case you grabbed the wrong one. :wink:
