### ISSUE TITLE
MacOS version is crashing

### ISSUE THREAD

**Issue by quwax** [sqlitebrowser/dbhub-application#3]
Hello,
the last version 3.9.1 is crashing directly after starting. 3.9.0 is working.
This is on MacOS 10.11.6 on a MacBookPro Retina.

**Comment by justinclift** [comment]
Sorry @quwax, I didn't realise people would file issues here for DB4S related stuff, so I wasn't watching.

If this is still happening for you, would you be ok to screenshot the error information or maybe cut-n-paste it here?  That would be helpful for investigating what is going wrong. :smile:

**Comment by justinclift** [comment]
Closing due to lack of response. 😦

**Comment by quwax** [comment]
no error information, as described before it opens and closes immediatly.
cheers
Matthias

**Comment by justinclift** [comment]
Ok.  It's difficult to determine the problem with just that. :wink:

If you start it from the command line instead, is any error information displayed?

For example:

```
$ /Applications/DB\ Browser\ for\ SQLite.app/Contents/MacOS/DB\ Browser\ for\ SQLite
Messages might be displayed here
```
