### ISSUE TITLE
Appcelerator Titanium compatibility on Android and iOS

### ISSUE THREAD

**Issue by corymalcolmtaylor** [sqlitebrowser/dbhub-application#5]
Hi,
Are the db files produced by this applications ver 3.9.1 compatible for use with Appcelerator Titanium mobile apps?  I have had no luck so far trying to install a very small database into my appcelerator alloy app wether testing in Android or iOS.   I'm not sure if I am doing something wrong or if there is a file format compatibility problem.

**Comment by justinclift** [comment]
Heh Heh Heh, you're probably looking for [this](https://github.com/sqlitebrowser/sqlitebrowser) project instead.

With that project, it creates SQLite database files, as should be useful for this:

&nbsp; &nbsp; https://wiki.appcelerator.org/display/guides2/Working+with+a+SQLite+Database

There is an (optional) encryption ability too, which can make the database file not look like a standard SQLite one.  But, if you haven't encrypted the database that won't come into play.

If you still haven't managed to figure it out, you might need to ping the Appcelerator people and provide them a copy of your database so they can check it.  Not really sure what else to suggest. :smile:

**Comment by corymalcolmtaylor** [comment]
Sorry, you are right I was looking for that other project.

**Comment by justinclift** [comment]
No worries at all, the project layout can be a bit confusing. :smile:

**Comment by justinclift** [comment]
Closing this now, as you've created an issue in the right spot now. :smile:
